### PR TITLE
Fixes compatibility issue w/ other plugins

### PR DESCRIPTION
**Pull request by sgrebnov**
1. Correct way to link android-support for Gradle build
2. Backward compatibility for Ant build

Example compatibility issue discussions:
https://github.com/phonegap-build/PushPlugin/issues/492
https://github.com/Wizcorp/phonegap-facebook-plugin/issues/1028
https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1032:

PS. Adding dependencies via corresponding gradle configuration is the only way to support multiple plugins which rely on the same dependency. If you use 'libs' folder then it will fail as gradle won't be able to rely on its smart [Dependency Managment/Versioning logic](https://docs.gradle.org/current/userguide/dependency_management.html)

### CODE REVIEW

**Comment by programming-kid** [comment]
hey can u create a fork with you changes for  facebook & push plug-ins, theses repos haven't been updated for long,

i tried to copy your solution but i am getting following error
```Could not find com.android.support:support-v13:21.0.0```  

pls can you help

**Comment by programming-kid** [comment]
here is the error what i get when i apply your pull request 
PushPlugin
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> A problem occurred configuring project ':com.phonegap.plugins.PushPlugin:appdev934524-android'.
   > Could not resolve all dependencies for configuration ':com.phonegap.plugins.PushPlugin:appdev934524-android:_debugCompile'.
      > Could not find com.android.support:support-v13:21.0.0.
        Searched in the following locations:
            https://jcenter.bintray.com/com/android/support/support-v13/21.0.0/support-v13-21.0.0.pom
            https://jcenter.bintray.com/com/android/support/support-v13/21.0.0/support-v13-21.0.0.jar
        Required by:
            android.com.phonegap.plugins.PushPlugin:appdev934524-android:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

```

Facebook Plugin
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> A problem occurred configuring project ':com.phonegap.plugins.facebookconnect:appdev934524-FacebookLib'.
   > Could not resolve all dependencies for configuration ':com.phonegap.plugins.facebookconnect:appdev934524-FacebookLib:_debugCompile'.
      > Could not find any version that matches com.android.support:support-v4:[20,21).
        Searched in the following locations:
            https://repo1.maven.org/maven2/com/android/support/support-v4/maven-metadata.xml
            https://repo1.maven.org/maven2/com/android/support/support-v4/
        Required by:
            android.com.phonegap.plugins.facebookconnect:appdev934524-FacebookLib:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.


```

where am i going wrong 
pls help
thanks

**Comment by kaansoral** [comment]
Just use these 2:
https://github.com/Telerik-Verified-Plugins/Facebook
https://github.com/Telerik-Verified-Plugins/PushNotification

The issue is fixed at those forks

**Comment by programming-kid** [comment]
hey @kaansoral  i tried those two repos but still i get error 

here are two repo m trying two install which i have forked and merged with @sgrebnov pull request 

https://github.com/programming-kid/PushPlugin
https://github.com/programming-kid/phonegap-facebook-plugin

My system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
OS: Distributor ID:	Ubuntu Description:	Ubuntu 14.04.1 LTS 
Node Version: v0.10.38

still i get above mentioned error 
thanks

**Comment by kaansoral** [comment]
You shouldn't get an error when you combine those plugins, I can't help you with this issue on your specific forks, however, I'm curious what the issue is when you use only these 2 plugins, as they are, without modifications

They both include a modified v4 android library that prevents the clash

**Comment by sgrebnov** [comment]
I'm closing my PR in favor of https://github.com/phonegap-build/PushPlugin/pull/588 as much more simple way to fix this (it does not support Ant, but as per discussion in Cordova dev mailing list we decided that it is not worth adding more complexity to support ant)

**Pull request closed without merging**
