### PR TITLE
Multiple Push Notification Issues

### PR DESCRIPTION
**Pull request by manjeshpv**
Cordova Phone Push Plugin Multiple Push Notifications Creating but not opening when tapped on the created notification

Always open last send push notification By Javascript Code

### CODE REVIEW

**Comment by mindcruzer** [comment]
+1 
Just noticed this issue in my app

**Comment by fskirschbaum** [comment]
If you import these changes you get symbol warnings... 

```
-compile:
    [javac] Compiling 4 source files to /[...clipped...]/trunk/platforms/android/ant-build/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] //[...clipped...]/trunk/platforms/android/src/com/plugin/gcm/GCMIntentService.java:87: error: cannot find symbol
    [javac] 			Random rand = new Random();
    [javac] 			^
    [javac]   symbol:   class Random
    [javac]   location: class GCMIntentService
    [javac] //[...clipped...]/trunk/platforms/android/src/com/plugin/gcm/GCMIntentService.java:87: error: cannot find symbol
    [javac] 			Random rand = new Random();
    [javac] 			                  ^
    [javac]   symbol:   class Random
    [javac]   location: class GCMIntentService
    [javac] //[...clipped...]/trunk/platforms/android/src/com/plugin/gcm/GCMIntentService.java:136: error: variable notId is already defined in method createNotification(Context,Bundle)
    [javac] 		int notId = 0;
    [javac] 		    ^
    [javac] 3 errors
    [javac] 3 warnings
```

**Comment by ghominejad** [comment]
@fskirschbaum  Two fixes :
```JAVA
import java.util.Random;

// line 88
notId = Integer.parseInt(extras.getString("notId",Integer.toString(rand.nextInt(1000))));
```

**Comment by jonmaim** [comment]
This PR + @ghominejad fix are solving the problem. Should be merged indeed.

**Comment by rysi3k** [comment]
Hello,
i have problem with this pull request. When I receive two notifications and open one of them, other one will disapper.
How to fix it?
Android 5 on Nexus 5

Regards.

**Comment by manjeshpv** [comment]
Try this https://github.com/AwardWallet/PushPlugin or https://github.com/manjeshpv/PushPlugin

**Comment by rysi3k** [comment]
@manjeshpv nope, the same effect :/

**Comment by manjeshpv** [comment]
Create a  git repo (https://github.com/new ) and send me link. I'll check...

**Comment by rysi3k** [comment]
@manjeshpv I have forked original PushPlugin from phonegap and copied my modifications over it. There is link for commit: https://github.com/rysi3k/PushPlugin/commit/86a8ab37ef7a1783cca166ba1a78c234c372965a

Dont look at iOS - there is working ok in original plugin.

I'm sending test notification with that code:
```
$this->post(json_encode([
            'registration_ids' => (array)$to,
            'data' => array(
                "message" => $message.' - '.($this->i++),
                'title' => $this->title,
                'params'=>$params,
                'notId'=>$this->i
            ),
]));
```

**Comment by williamazevedodepaula** [comment]
I have made an approach to solve this issue. Please take a look in:

https://github.com/williamazevedodepaula/PushPluginExt/blob/master/README.md

In this version, when there are many notifications, clicking on any of them will call the callback function for any of the pending notifications, with an interval of 300 milisseconds between them. The msgcnt on each notification will show the order the notification were received.

The solution is not very ellegant, but do the work!
I will like sugestions!!
Thanks!

**Comment by 05bca054** [comment]
Hello williamazevedodepaula,

Thanks for your solution but can you explain how to technically implement it.I tried to copy and replace those four files from your plugin(https://github.com/williamazevedodepaula/PushPluginExt/tree/master/src/android/com/plugin/gcm) but still no luck.

Please advise.

-Niks

**Comment by williamazevedodepaula** [comment]
Hello  05bca054,

There is no special usage. It must be used exactly the same way the original Plugin.
I will check to see if there is any problem.
Could you provide me the peace of code where you used this?
When i have the solution, i tell you!!

Best regards!!

**Comment by 05bca054** [comment]
Thanks for your time and consideration.here is my code

case 'message':
	alert(e.payload.coupon_id+" --:-- "+e.payload.notId);//This called only once even if multiple notification is there in notification tray
	if ( e.foreground )
	{
                 ..............
        }

PHP passing parameter as payload

$data = array
(
	'message' 	=> 'Nice n new gifts',
	'title'		=> 'Perfumme sale',		
	//'subtitle'	=> 'This is a subtitle. subtitle',
	'coupon_id'	=>	161,
	'notId'		=>	161
);

Feel free to ask for more information if needed.

-Niks

**Comment by williamazevedodepaula** [comment]
Sorry for spending so much time...i was a little busy!
Try to remove the "payload" from your call. The plugin removes the properties of payload and puts it directly in the object. Try this:

alert(e.coupon_id+" --:-- "+e.notId);

It may be causing a access on a undefined property, causing the application to halt.
Anyway, there is an error in my version of the plugin: every time the callback is called, an debug alert is shown. I removed it and will commit this now, so i suggest you to pull again!

Best regards,
William Azevedo de Paula

**Comment by ritvick** [comment]
This issue is still not resolved . I forked from https://github.com/manjeshpv/PushPlugin and used it.

Below are two notifications which I send. Both Overlaps and only the latest notification is passed in callback. 
My structure is 
{
  "registration_ids" : [".."],
  
 "data" : {
    "message":"Test3",
"title": "Test3",
"msgcnt":1,
"notId":3
  }
}

{
  "registration_ids" : [".."],
  
 "data" : {
    "message":"Test1",
"title": "Test1",
"msgcnt":1,
"notId":1
  }
}

**Comment by ritvick** [comment]
https://github.com/manjeshpv/PushPlugin/pull/2

**Pull request closed without merging**
